import type { Metadata } from 'next'
import { Barlow } from 'next/font/google'
import './globals.scss'
import Container from "@/components/Container/Container";
import Header from "@/components/Header/Header";

const barlow = Barlow({
  variable: '--barlow-font',
  weight: ['400', '500','600','700', '800'],
  style: 'normal',
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: 'A Digital Product Studio That Will Work',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={barlow.variable}>
      <body>
      <Header/>
      <main>
        <Container>
          {children}
        </Container>
      </main>
      </body>
    </html>
  )
}
